### PR TITLE
Two misspellings

### PR DESCRIPTION
**Pull request by Hauwertlhaufn**
Fixed two misspellings.

### CODE REVIEW

**Comment by samueltardieu** [comment]
Please `rebase -i` or `cherry-pick` your commit in a new branch so that we do not import all the "Merge pull request" commits in the process.

**Comment by Hauwertlhaufn** [comment]
Sorry, I have problems to cherry-pick.  Could you do that? Otherwise I will look after it in a few days, when I have the time to do so. Sorry for your effort, I just developed locally before.

**Comment by samueltardieu** [comment]
Done. Thanks for your contribution.

**Comment by Hauwertlhaufn** [comment]
Thank you very much.

**Pull request closed without merging**
