### PR TITLE
Landing page for WhereYouGo

### PR DESCRIPTION
**Pull request by Lineflyer**
@mucek4 
Proposal for a interim solution to just have something behind whereyougo.org
You would then need to forward it to https://www.cgeo.org/whereyougolanding

If we want to create support@whereyougo.org we need to change that on the new page.

### CODE REVIEW

**Comment by Lineflyer** [comment]
@mucek4 Friendly reminder

**Comment by Lineflyer** [comment]
@mucek4 Please redirect as suggested above if you find time. Thanks.

**Comment by mucek4** [comment]
Try it.

**Comment by Lineflyer** [comment]
Works! Thank you!

**Pull request merged**
