### PR TITLE
"Vectorize" the social media icons

### PR DESCRIPTION
**Pull request by brainscript**
I thought I would be time to ...
- **replace the social media icons** (`*.png`) with scalable vector graphics (`*.svg`)
- **update the Google+ icon** to the newer version according to the [branding guidelines](https://developers.google.com/+/branding-guidelines)
- **add a simple transition effect**

The **new icons look almost exactly the same** as the old `*.png` icons, but ...
- the page loads **faster**
- you can zoom in and the icon  **won't get blurry**
- they have a **nice and smooth transition** effect
- svg is **the future** :smile:

**I hope you like the icons.**

As soon as I have time I will vectorize the other images on the page,
for example the download buttons (Play Store and APK).

### CODE REVIEW

**Comment by rsudev** [comment]
Are those svg icons you own creation? I would assume all of these graphics are registered trademarks and come with long legal documents that regulate their usage. I guess, we copied the existing pngs from their source sites when we created the page (I don't know if that was 'legal' in the first place).
Any comment on that (also from the greater audience)?

**Comment by brainscript** [comment]
@rsudev
In case of Twitter and G+ I took the icons are **from their logo/brand kit**. Then I added the surrounding circle, scaled and repositioned them and changed the color to white.

I also checked the corresponding **brand guidelines** and as far as I can tell, they're fine with it.

In case of the Facebook icon I used the png as a background and then "vectored" the "f" over it.
If needed I can redo that using their logo kit.

**Comment by brainscript** [comment]
I just checked the [Facebook brand site](https://www.facebookbrand.com/) and they only have an "f" inside a box.

Facebook f

But there's also no rule saying you can't put the "f" inside another shape (a circle in our case).

**Comment by brainscript** [comment]
Mmmhh ... http://www.flaticon.com/free-icon/facebook-logo_59439

**Comment by rsudev** [comment]
According to facebook, they would not like it (facbook identity guide light, p68):
```
Incorrect Use
To ensure accurate and consistent use, never alter, rotate, 
embellish or attempt to recreate the “f” logo. Don’t alter 
the rounded box shape or alter the proportions, or add any 
embellishments.
```
But that affects our current design as well...
Not sure if they have the power to enforce that, should the choose to do so.

**Comment by brainscript** [comment]
Screenshot
Here's a screenshot of the icons on the page, I forgot to include it in the first post.

**Comment by SammysHP** [comment]
Thank you, these icons look great. I think it is ok to use them. Usage guidelines are usually really strict, but are rarely enforced.

I squashed and merged your commits. The transition is a little bit long, so I changed it to 0.2s instead of one second. However the transition is also applied after page load, so the icons are flashing/fading at the beginning. AFAIK you can prevent this only via JavaScript. Thus I removed the transition (we do not use it for other elements anyway).

**Comment by SammysHP** [comment]
Merged manually in 64ea53654a2790327c87e94fc8be8fbc7b663f07.

**Comment by brainscript** [comment]
@SammysHP Nice! :smile:

**Comment by SammysHP** [comment]
> As soon as I have time I will vectorize the other images on the page,
for example the download buttons (Play Store and APK).

You can also propose new images if you want.

**Pull request closed without merging**
