### PR TITLE
Add connectors statistics

### LINKED ISSUE #188: Add connector statistics in status page
This is related to https://github.com/cgeo/cgeo/issues/7214 and https://github.com/cgeo/cgeo-status/issues/20. The client and server sides have been implemented, and now some Javascript code must be added to the status page.

As I was not able to setup a working Jekyll environment in the time I had scheduled for this, I'll let someone else (@SammysHP comes to mind) do it.

The new API is documented in cgeo-status routes.conf:

```
# Get counter by active connector
# The data is returned as a map with some special keys:
#   - _noinfo contains the number of clients with no connector information (older ones)
#   - _withinfo contains the number of clients with connector information
#   - _noconnectors contains the number of clients with empty (but present) connector information
```

One could display the percentage for every meaningful connector (keys not starting with `"_"` divided by `_withinfo` times 100), as well as the percentage of uses with no connector active (`_noconnectors` divded by `_withinfo` times 100).

### PR DESCRIPTION
**Pull request by okainov**
Hopefully fixes #188

TBH I didn't try it since I don't have proper build environment, but the logic seemed simple enough. Please try and if it's fine then merge so we can finally see the connectors reports :)

Mention @Lineflyer

### CODE REVIEW

**Comment by Lineflyer** [comment]
@samueltardieu Would you mind giving this a review?

**Comment by samueltardieu** [comment]
As I noted in #188 I don't have the proper environment to test it, it would take me too much time to install it and I have none right now.

**Comment by okainov** [comment]
Thanks to modern technologies and Docker, I was able to build the website to actually see it in 10 minutes.

It works. Should be enough?

image

**Comment by Lineflyer** [comment]
Thanks for your contribution @okainov

**Comment by Lineflyer** [comment]
@okainov @samueltardieu 
Looking at https://www.cgeo.org/status.html after merging this I wonder, that the total sum of users is the same in version view and connector view.
That is most likely not correct, because some people will for sure have more than one connector active simultaneously.
So, expectation is: usersbyconnectors >= usersbyversion, whereas both being equal is unlikely.

**Comment by okainov** [comment]
>Looking at https://www.cgeo.org/status.html after merging this, I wonder that the total sum of users is the same in version view and connector view.
That is most likely not correct, because some people will for sure have more than one connector active simultaneously.
So, expectation is: usersbyconnectors >= usersbyversion, whereas both being equal is unlikely.

Am, hm, umm, yeah, kind of, because of https://github.com/cgeo/cgeo.github.io/blob/master/status.html#L149. So "total" is amount of users, not amount of connectors used. What one could also easily notice is that "Total" is much less than sum of connectors values :) Also that's why the percentage is calculated by users, not by connectors (which IMO makes sense, we want to know how many users are using each connector).

=> so the fields look fine, the only question is about "total". I don't know, I'm not sure showing total amount of connectors makes sense, but up to you, what you want to see there?

**Comment by Lineflyer** [comment]
You are right, I should have looked into the details of it.

> => so the fields look fine, the only question is about "total". I don't know, I'm not sure showing total amount of connectors makes sense, but up to you, what you want to see there?

From the graphic appearance IMHO the total amount of connectors would make more sense, as it gives an idea (comparing it with the total above) about how many users use more than one connector.

**Pull request merged**
