### PR TITLE
add info about account switching to FAQ

### PR DESCRIPTION
**Pull request by moving-bits**
follow-up to support ticket #655547

### CODE REVIEW

**Comment by Lineflyer** [comment]
IMHO such workaround for multi-user creates more problems than it solves when inexperienced users try it.
e.g. all stored caches found state and other data are still shown from perspective of user 1 while being logged in as user 2. At least this should IMHO be mentioned.

**Comment by moving-bits** [comment]
Hm, you're right. I thought there was something user-dependent, but couldn't remember what. ("Found state" could have been detected by comparing user names, but it's probably stored as a flag, which would be user-specific.)
I'll add this to the PR.

**Comment by Lineflyer** [comment]
In any case I think there is no broad use case behind.  Cheap Android devices are out there for well below <100€. I would rather buy on of these instead of juggling around with multiple users just to log caches for the whole family (or similar).

**Comment by moving-bits** [comment]
Use-case in that specific support issue was change of user accounts (not day-to-day switching), but we had questions about using multiple accounts as well in the past. I'll adapt the headline to favor the account change to using multiple accounts.

**Pull request merged**
