### PR TITLE
Use https in heatmap's links and tiles URLs

### PR DESCRIPTION
**Pull request by samueltardieu**

### CODE REVIEW

**Comment by SammysHP** [comment]
This might not work if accessing a local copy via file:// (something that should not happen usually). Any reason for not using TLS by default?

**Comment by SammysHP** [comment]
Also we should keep the `{s}` for parallel access.

**Comment by samueltardieu** [comment]
> Also we should keep the `{s}` for parallel access.

They don't have a valid certificate for those sites. And you're not supposed to use a local copy indeed (jekyll serve and base attribute are here for that), but I can make it https by default anyway.

**Comment by samueltardieu** [comment]
Note that the patch is untested.

**Pull request merged**
