### PR TITLE
New vector donate button

### PR DESCRIPTION
**Pull request by brainscript**
_Part of my #105 todo list ..._

Preview:
donatebutton

### CODE REVIEW

**Comment by SammysHP** [comment]
This looks good. The icons do not flash anymore, too. But I'd prefer the text without jitter (just the slightly rotated heart). The label says "Donate (PayPal)" which sounds redundant. Maybe a bit longer like "Support us via PayPal".

**Comment by brainscript** [comment]
@SammysHP I just took the label from the old button. I will change it.

**Comment by SammysHP** [comment]
Sorry for the late reply. I thought that this PR was already merged. Thanks for your contribution!

**Comment by brainscript** [comment]
@SammysHP That's probably because you expected me to make some changes to the text (remove the "jittering") what I wasn't able to do, because I switched to Ubuntu GNOME in the meantime and I didn't remember the name of the font I used ... :smile_cat:

**Pull request merged**
