### PR TITLE
Use proper typographic characters for minutes and seconds

### PR DESCRIPTION
**Pull request by UniQP**
This also adds missing primes for the MinDec example.

### CODE REVIEW

**Comment by SammysHP** [comment]
IMHO we should keep the commonly used format. I've never seen a geocacher who uses a prime symbol. Moreover most users would have problems typing it. ;)

**Comment by UniQP** [comment]
It's a website, they should read it.

**Comment by SammysHP** [comment]
But it is an explanation for the users.

> c:geo supports geocoordinate notations in the following formats:

And users see a prime symbol and think: "WTF, how should I type this‽" ¹


¹ Yeah, I used a cool unicode interrobang instead of a boring ?!

**Comment by UniQP** [comment]
I don't expect that to be a problem. It's all based on copy and paste.

Let's see what the others think about it.

**Comment by SammysHP** [comment]
As nobody else commented this PR let's keep the old (and simple) version.

**Pull request closed without merging**
